### ISSUE TITLE
Direction flex test is solved in 50% already 

### ISSUE THREAD

**Issue by johny** [jondot/ReactNativeKatas#10]
Second kata about direction is almost solved: 

`<View style={{flexDirection:'row'}}>`

**Comment by jondot** [comment]
Hi @johny, not sure what you mean, but basically there are many ways to solve a kata. It allows you to have creative freedom, so that you don't have to do what's done in the solution to solve it. It may be that you found a more elegant solution than the official one - in which case I'll gladly accept a PR!

**Comment by jondot** [comment]
Is now fixed.
