### ISSUE TITLE
Unhandled JS Exception: Invariant Violation

### ISSUE THREAD

**Issue by lpitteloud** [jondot/ReactNativeKatas#16]
Hi,

Thank you for your work, but I'm not able to run it properly on iOs Simulator. 
After launching the app with react-native, I've got the following error message : 

`Unhandled JS Exception: Invariant Violation: Module name prefixes should've been stripped by the native side but wasn't for RCTJSCExecutor
`

Is it due to my version of React Native ?

react-native-cli: 1.2.0
react-native: 0.33.0

**Comment by thoth70** [comment]
I have this issue also. Versions of react-native-cli and react-native are the same as above.

**Comment by bikemansam** [comment]
I have also run into this issue.

**Comment by kiernan** [comment]
works at the moment with:
react-native-cli: 2.0.1
react-native: 0.33.0

**Comment by jhampton** [comment]
Just throwing my experience into this bucket.  I had similar issues during a RN upgrade (0.35 -> 0.39).  I had to run a full "Clean Build Folder..." (Product...Hold down Option...Clean Build Folder) in order to clear out the old binaries.  We also had some npm module changes, so I had already run a full rm -rf node_modules && npm install (or yarn install if you're a cool kid, I suppose).

HTH

**Comment by jhampton** [comment]
Just throwing my experience into this bucket.  I had similar issues during a RN upgrade (0.35 -> 0.39).  I had to run a full "Clean Build Folder..." (Product...Hold down Option...Clean Build Folder) in order to clear out the old binaries.  We also had some npm module changes, so I had already run a full rm -rf node_modules && npm install (or yarn install if you're a cool kid, I suppose).

HTH

**Comment by jondot** [comment]
Thanks guys, good answers. These kinds of cache artifacts plague normal iOS development regardless of React Native.
I'll tag this as "Q&A", for other people to find, and close it since i'm doing a bit of cleanups in the repo.
