### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by DanielMSchmidt** [jondot/ReactNativeKatas#2]
Hi there,

Thank you so much for this awesome project, I plan to use these Katas at a little training session I am planning to do. For this reason, I would like to extend the Katas, to contain more examples, like how to use ListViews, Scroll Views or other RN specific components. 

Is there a guide on how to do so or could you add a brief one?

Have a nice day!

**Comment by jondot** [comment]
Hi Daniel, this is exciting news!
It should be very doable - remember these katas test visuals (it literally takes snapshots) so styling, data and composition are great candidates however interactions are not a goal because then we'd need to test animation.
I have a guide for kata builders that will be done today, I'll link here when done :)

**Comment by jondot** [comment]
Done, here: https://github.com/jondot/ReactNativeKatas/blob/master/docs/kata_builders.md

**Comment by DanielMSchmidt** [comment]
Sorry, training session did not happen, but thanks for your help anyways ;)
