### ISSUE TITLE
Error when running iOS

### ISSUE THREAD

**Issue by M-Moghazi** [jondot/ReactNativeKatas#21]
can't run it on iOS, getting the error below

'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>

**Comment by royisch** [comment]
same here

**Comment by pilaas** [comment]
I've upgraded all package.json libs, run instructions from this tweet (https://twitter.com/skellock/status/818813810781908992) and rewrite `#import "RCTRootView.h"` into `#import <React/RCTRootView.h>` in AppDelegate.m and it worked.

**Comment by M-Moghazi** [comment]
it was fixed by changing #import <React/RCTBridgeModule.h> to #import <RCTBridgeModule.h>
I had only to delete React from import

**Comment by jondot** [comment]
@pilaas it might save us a bit of time if you could submit your changes as a PR. Would you be willing to do that?

As a sidenote:

0.40 have introduced breaking changes which are exactly what you've experienced. I wasn't in a hurry to upgrade since not all people did the move yet (it means you will need to look for a compatible library for every native library that you use). I think since there are enough people bumping into this, we're OK to make the move.

**Comment by pilaas** [comment]
@jondot I've missed notification. Sure, I'll make PR.
