### ISSUE TITLE
this._nativeModule.addListener is not a function

### ISSUE THREAD

**Issue by marcpechaitis** [jondot/ReactNativeKatas#3]
Hi I just discovered these katas (via the comments in the deco slack channel) and wanted these to give these exercises a try...however I just ran into an issue when I tried to spin it up for the first time:

![screen shot 2016-06-19 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/12177541/16179484/874e5510-3624-11e6-9903-a569c6ecb67f.png)

steps I took:
1) cloned the repo
2) `cd ReactNativeKatas`
3) `npm i`
4) `react-native run-ios`
(screenshot posted above shows what happens in the simulator)

I'm kinda new at this, so I wanted to bring to your attention before I dig in to see what could be the cause...thanks!

_Personal note, I also bought your book and am enjoying what I've seen so far!_

**Comment by jondot** [comment]
Hi,
Thanks for the kind words! I hope you'll enjoy the book till the end :)

For your error, it is hard to discern what exactly is the causer, but I'm looking at traces of `websocket` there, so, is it possible that the packager is not up or didn't yet finish crawling the file system? (i.e. the solution is to - 1. check that the packager terminal window popped up, and, 2. wait a bit so that it would do its thing)

**Comment by marcpechaitis** [comment]
Thanks @jondot,
I simply closed my terminal window session and when I re-opened and tried again and it looks like things are working now:

![screen shot 2016-06-19 at 3 28 47 pm](https://cloud.githubusercontent.com/assets/12177541/16179936/941bbcb6-3632-11e6-8d0c-6f05a6f88b94.png)

Thanks!

**Comment by jondot** [comment]
Awesome! happy to see you've solved it!
